### ISSUE TITLE
显示 “预约时间段不存在！” 

### ISSUE THREAD

**Issue by Xianwei-Zhou** [wangshouh/sdufelib_seat_crawler#1]
2022/4/12抢座时出现该问题。
另外请问一下在 book_seat 函数中，服务器是根据referer_url中的日期来判断应该抢哪天的吗？比如 Referer 为 ‘http://libst.sdufe.edu.cn/web/seat3?area=39&segment=1307889&day=2022-04-14&startTime=08:00&endTime=22:00’ 时代表抢2022-4-14的？

**Comment by Xianwei-Zhou** [comment]
已解决，我refer中的segment写错了

**Comment by wangshouh** [comment]
经过测试，服务器仅要求存在referer参数，而不会检查内容，在最新的通过v2.0版本中已去除大部分无用参数和函数，进行了大量代码精简，并换用aiohttp库异步爬取提高性能，您可以参阅其中代码。

**Comment by Xianwei-Zhou** [comment]
是的，我测试时也发现服务器不会检查refer内容，是根据segment确定日期的。在您的get_api_list方法中获取segment可以使用 url= 'http://libst.sdufe.edu.cn/api.php/v3areas/{}/date/{}'.format(floor, date) 获取指定日期的segment。
另外我似乎没有看见最新的v2.0版本

**Comment by wangshouh** [comment]
忘记打tag了，您可以重新拉取一下仓库

**Comment by Xianwei-Zhou** [comment]
学到了，异步比非异步速度提升了接近5倍。
我测试了一下整个get_available_seat的速度，对3-7层共20个区域扫描100遍，得到的时间是300.2s，而不使用异步直接单线程得到的结果是313.7s，差别不大。然后测每部分时间发现主要耗时在文件读取上，如果仅进行一次文件读取然后将其保存为全局变量耗时仅69.5s。
